Fixing clock divider calculations.
adafruit/Adafruit_ZeroI2S pull request #14
Opened 2022-12-31 20:12 UTC by sah

There were several problems:

- Using int floor division, mckoutdiv was sometimes winding up far from the ideal value (e.g. at 48kHz, 48M/(48k*256)=3.90625, which was being floored to 3). Rounding selects something closer to the desired rate.

- High sample rates can have an ideal divider that rounds down to 0. We can't go below 1.

- To avoid distortion, the SCK frequency needs to evenly divide the MCK frequency. Basing them both independently on the target sample rate means that sometimes they can wind up incommensurate when we can't perfectly achieve the desired clock rates using the provided int clock dividers. Instead, after calculating an mckoutdiv divider to get the closest available clock rate for MCK, we can explicitly calculate an mckdiv divider to produce the SCK rate that divides MCK correctly.

2023-05-16 14:00 UTC, dhalbert requested changes

2023-05-16 14:00 UTC, dhalbert commented on Adafruit_ZeroI2S.cpp
> +      max(round(static_cast<double>(gclkFreq) / nominalMckFreq), 1);
Using `double`s here will drag in software floating point routines that might not be included otherwise. Can you do the rounding just with integers? If that is not possible, could you use `float`, which will be smaller, and native on M4 processors?

2023-05-16 16:37 UTC, sah commented on Adafruit_ZeroI2S.cpp
> +      max(round(static_cast<double>(gclkFreq) / nominalMckFreq), 1);
Makes sense. I'll see what I can do!

2023-05-16 17:51 UTC, sah commented
Maybe I can also draw your attention to https://github.com/adafruit/Audio/pull/7 where I fixed a more minor inconvenience in the Audio library.

2023-05-25 14:44 UTC, dhalbert approved these changes
Thanks for the change to int arithmetic!

2023-05-25 14:45 UTC, merged